// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAthXgeU-Yt4d24HO-TpIqvoLExzlWkOHY',
    appId: '1:247911586643:web:1f2d6239d1fe0daab4dfa6',
    messagingSenderId: '247911586643',
    projectId: 'crop-shield-ai-hamna-8b574',
    authDomain: 'crop-shield-ai-hamna-8b574.firebaseapp.com',
    storageBucket: 'crop-shield-ai-hamna-8b574.firebasestorage.app',
    measurementId: 'G-SB66XF5VDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOIvzFPlzFoCoj-ReyVP6B_K9i6RZq1Us',
    appId: '1:247911586643:android:8e1fa0a14041a7e7b4dfa6',
    messagingSenderId: '247911586643',
    projectId: 'crop-shield-ai-hamna-8b574',
    storageBucket: 'crop-shield-ai-hamna-8b574.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHXrciNbC2gVNtwVHH1c6yR9XuDaWdHpE',
    appId: '1:247911586643:ios:824fdbd544269eddb4dfa6',
    messagingSenderId: '247911586643',
    projectId: 'crop-shield-ai-hamna-8b574',
    storageBucket: 'crop-shield-ai-hamna-8b574.firebasestorage.app',
    iosBundleId: 'com.example.cropShieldAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHXrciNbC2gVNtwVHH1c6yR9XuDaWdHpE',
    appId: '1:247911586643:ios:824fdbd544269eddb4dfa6',
    messagingSenderId: '247911586643',
    projectId: 'crop-shield-ai-hamna-8b574',
    storageBucket: 'crop-shield-ai-hamna-8b574.firebasestorage.app',
    iosBundleId: 'com.example.cropShieldAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAthXgeU-Yt4d24HO-TpIqvoLExzlWkOHY',
    appId: '1:247911586643:web:b0f204f5d9e67f68b4dfa6',
    messagingSenderId: '247911586643',
    projectId: 'crop-shield-ai-hamna-8b574',
    authDomain: 'crop-shield-ai-hamna-8b574.firebaseapp.com',
    storageBucket: 'crop-shield-ai-hamna-8b574.firebasestorage.app',
    measurementId: 'G-16CWQ54N9L',
  );
}
